name: Deploy SportApp API
on: 
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x
           
            - name: Install dependencies
              run: dotnet restore ./SportApp_BE/SportApp_BE.csproj

            - name: Build 
              run: dotnet build ./SportApp_BE/SportApp_BE.csproj --configuration Release --no-restore


