name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  AZURE_WEBAPP_NAME: "SportAppDemo"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./SportApp.sln
      - name: Build
        run: dotnet build ./SportApp.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test ./UnitTest/UnitTest.csproj
      - name: Publish
        run: dotnet publish ./SportApp_BE/SportApp_BE.csproj --configuration Release --no-build --output ./publish
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v4
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish
